-- MySQL Script generated by MySQL Workbench
-- Fri Oct 21 14:42:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALUNO` (
  `ALU_MATRICULA` INT NOT NULL AUTO_INCREMENT,
  `ALU_NOME` VARCHAR(45) NULL,
  `ALU_EMAIL` VARCHAR(45) NULL,
  `ALU_SENHA` VARCHAR(45) NULL,
  `ALU_RESPOSTA` VARCHAR(45) NULL,
  PRIMARY KEY (`ALU_MATRICULA`));


-- -----------------------------------------------------
-- Table `mydb`.`BIOMETRIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BIOMETRIA` (
  `BIO_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `BIO_DIGITAL` VARCHAR(45) NULL,
  `ALUNO_ALU_MATRICULA` INT NOT NULL,
  PRIMARY KEY (`BIO_CODIGO`, `ALUNO_ALU_MATRICULA`),
  INDEX `fk_BIOMETRIA_ALUNO_idx` (`ALUNO_ALU_MATRICULA` ASC) VISIBLE,
  CONSTRAINT `fk_BIOMETRIA_ALUNO`
    FOREIGN KEY (`ALUNO_ALU_MATRICULA`)
    REFERENCES `mydb`.`ALUNO` (`ALU_MATRICULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`TIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO` (
  `TIP_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `TIP_ENTRADA` VARCHAR(45) NULL,
  `TIP_SAIDA` VARCHAR(45) NULL,
  PRIMARY KEY (`TIP_CODIGO`));


-- -----------------------------------------------------
-- Table `mydb`.`EVENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EVENTO` (
  `EVE_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `BIOMETRIA_BIO_CODIGO` INT NOT NULL,
  `BIOMETRIA_ALUNO_ALU_MATRICULA` INT NOT NULL,
  `TIPO_TIP_CODIGO` INT NOT NULL,
  PRIMARY KEY (`EVE_CODIGO`, `BIOMETRIA_BIO_CODIGO`, `BIOMETRIA_ALUNO_ALU_MATRICULA`, `TIPO_TIP_CODIGO`),
  INDEX `fk_EVENTO_BIOMETRIA1_idx` (`BIOMETRIA_BIO_CODIGO` ASC, `BIOMETRIA_ALUNO_ALU_MATRICULA` ASC) VISIBLE,
  INDEX `fk_EVENTO_TIPO1_idx` (`TIPO_TIP_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_EVENTO_BIOMETRIA1`
    FOREIGN KEY (`BIOMETRIA_BIO_CODIGO` , `BIOMETRIA_ALUNO_ALU_MATRICULA`)
    REFERENCES `mydb`.`BIOMETRIA` (`BIO_CODIGO` , `ALUNO_ALU_MATRICULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENTO_TIPO1`
    FOREIGN KEY (`TIPO_TIP_CODIGO`)
    REFERENCES `mydb`.`TIPO` (`TIP_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
